### ISSUE TITLE
3.2.8agent启动失败，没有任何日志

### ISSUE THREAD

**Issue by w39021384** [tianshiyeben/wgcloud#22]

**Comment by w39021384** [comment]
服务器是华为鲲鹏，arm架构

**Comment by tianshiyeben** [comment]
你看下是不是没有，可执行权限，wgcloud-agent-release，或者你用sudo



---原始邮件---
发件人: "w39021384"<notifications@github.com&gt;
发送时间: 2020年11月24日(周二) 下午2:48
收件人: "tianshiyeben/wgcloud"<wgcloud@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [tianshiyeben/wgcloud] 3.2.8agent启动失败，没有任何日志 (#22)

**Comment by tianshiyeben** [comment]
没有明白哈，是不支持吗，我没有用过这个服务器



---原始邮件---
发件人: "w39021384"<notifications@github.com&gt;
发送时间: 2020年11月24日(周二) 下午3:03
收件人: "tianshiyeben/wgcloud"<wgcloud@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: Re: [tianshiyeben/wgcloud] 3.2.8agent启动失败，没有任何日志 (#22)




 
服务器是华为鲲鹏，arm架构

**Comment by w39021384** [comment]
> 没有明白哈，是不支持吗，我没有用过这个服务器
> […](#)
> ---原始邮件--- 发件人: "w39021384"<notifications@github.com&gt; 发送时间: 2020年11月24日(周二) 下午3:03 收件人: "tianshiyeben/wgcloud"<wgcloud@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: Re: [tianshiyeben/wgcloud] 3.2.8agent启动失败，没有任何日志 (#22) 服务器是华为鲲鹏，arm架构 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

应该是go编译出来的可执行文件，不支持arm架构

**Comment by w39021384** [comment]
> 没有明白哈，是不支持吗，我没有用过这个服务器
> […](#)
> ---原始邮件--- 发件人: "w39021384"<notifications@github.com&gt; 发送时间: 2020年11月24日(周二) 下午3:03 收件人: "tianshiyeben/wgcloud"<wgcloud@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: Re: [tianshiyeben/wgcloud] 3.2.8agent启动失败，没有任何日志 (#22) 服务器是华为鲲鹏，arm架构 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

X86服务器上正常

**Comment by w39021384** [comment]
执行./wgcloud-agent-release

**Comment by w39021384** [comment]
执行./wgcloud-agent-release
报错-bash: ./wgcloud-agent-release: cannot execute binary file

**Comment by tianshiyeben** [comment]
你执行那个start.sh



---原始邮件---
发件人: "w39021384"<notifications@github.com&gt;
发送时间: 2020年11月24日(周二) 下午5:31
收件人: "tianshiyeben/wgcloud"<wgcloud@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"tianshiyeben"<tianshiyeben@qq.com&gt;;
主题: Re: [tianshiyeben/wgcloud] 3.2.8agent启动失败，没有任何日志 (#22)




 
执行./wgcloud-agent-release
 报错-bash: ./wgcloud-agent-release: cannot execute binary file

**Comment by w39021384** [comment]
> 你执行那个start.sh
> […](#)
> ---原始邮件--- 发件人: "w39021384"<notifications@github.com&gt; 发送时间: 2020年11月24日(周二) 下午5:31 收件人: "tianshiyeben/wgcloud"<wgcloud@noreply.github.com&gt;; 抄送: "Comment"<comment@noreply.github.com&gt;;"tianshiyeben"<tianshiyeben@qq.com&gt;; 主题: Re: [tianshiyeben/wgcloud] 3.2.8agent启动失败，没有任何日志 (#22) 执行./wgcloud-agent-release 报错-bash: ./wgcloud-agent-release: cannot execute binary file — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

执行start.sh没有任何反应，也没有日志，单独执行./wgcloud-agent-release就会报上面那个错误

**Comment by tianshiyeben** [comment]
晕



---原始邮件---
发件人: "w39021384"<notifications@github.com&gt;
发送时间: 2020年11月24日(周二) 晚上6:00
收件人: "tianshiyeben/wgcloud"<wgcloud@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"tianshiyeben"<tianshiyeben@qq.com&gt;;
主题: Re: [tianshiyeben/wgcloud] 3.2.8agent启动失败，没有任何日志 (#22)




  
你执行那个start.sh
 …
 ---原始邮件--- 发件人: "w39021384"<notifications@github.com&gt; 发送时间: 2020年11月24日(周二) 下午5:31 收件人: "tianshiyeben/wgcloud"<wgcloud@noreply.github.com&gt;; 抄送: "Comment"<comment@noreply.github.com&gt;;"tianshiyeben"<tianshiyeben@qq.com&gt;; 主题: Re: [tianshiyeben/wgcloud] 3.2.8agent启动失败，没有任何日志 (#22) 执行./wgcloud-agent-release 报错-bash: ./wgcloud-agent-release: cannot execute binary file — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
  
执行start.sh没有任何反应，也没有日志，单独执行./wgcloud-agent-release就会报上面那个错误

**Comment by tianshiyeben** [comment]
是不是文件没有下载完整，或者你在其他的linux试试


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tianshiyeben/wgcloud"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月24日(星期二) 晚上6:00
收件人:&nbsp;"tianshiyeben/wgcloud"<wgcloud@noreply.github.com&gt;;
抄送:&nbsp;"val"<tianshiyeben@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [tianshiyeben/wgcloud] 3.2.8agent启动失败，没有任何日志 (#22)





  
你执行那个start.sh
 …
 ---原始邮件--- 发件人: "w39021384"<notifications@github.com&gt; 发送时间: 2020年11月24日(周二) 下午5:31 收件人: "tianshiyeben/wgcloud"<wgcloud@noreply.github.com&gt;; 抄送: "Comment"<comment@noreply.github.com&gt;;"tianshiyeben"<tianshiyeben@qq.com&gt;; 主题: Re: [tianshiyeben/wgcloud] 3.2.8agent启动失败，没有任何日志 (#22) 执行./wgcloud-agent-release 报错-bash: ./wgcloud-agent-release: cannot execute binary file — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
  
执行start.sh没有任何反应，也没有日志，单独执行./wgcloud-agent-release就会报上面那个错误

**Comment by tianshiyeben** [comment]
华为鲲鹏cpu无法启动agent问题处理，请查看第9说明，http://www.wgstart.com/docs13.html
