### ISSUE TITLE
docker?

### ISSUE THREAD

**Issue by 1157457050** [tianshiyeben/wgcloud#35]

**Comment by tianshiyeben** [comment]
docker监控模块，请到网站www.wgstart.com下载使用

**Comment by 1157457050** [comment]
我想问的是有没有docker 直接部署的。

**Comment by tianshiyeben** [comment]
这样啊，没有直接部署的，但是可以做成docker镜像，在这
https://blog.csdn.net/tianshiyeben/article/details/118756889




---Original---
From: ***@***.***&gt;
Date: Mon, Sep 13, 2021 18:59 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [tianshiyeben/wgcloud] docker? (#35)




 
我想问的是有没有docker 直接部署的。
 
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
